### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by pythonSB** [zimnyaa/3snake-kinit#1]
I don't know if you are interested in continuing to maintain this project, because it is not easy to record passwords now. Wrong passwords are recorded. If someone has a lot of wrong passwords, this is not a good thing.

**Comment by zimnyaa** [comment]
I'm assuming you mean that the password is still recorded if the authentication fails (the password was incorrect)?

**Comment by pythonSB** [comment]
> I'm assuming you mean that the password is still recorded if the authentication fails (the password was incorrect)?

Yes, brother, when others are blasting the current sshd, the wrong password will be recorded, which will cause the password file to be bloated.

**Comment by zimnyaa** [comment]
Oh, then it is not an issue of the fork, since all SSH-related functionality is unchanged from the original 3snake project.

**Comment by pythonSB** [comment]
> Oh, then it is not an issue of the fork, since all SSH-related functionality is unchanged from the original 3snake project.

I'm sorry, but I'll pay you if you can fix this.
